### ISSUE TITLE
Multiple "TypeError: integer argument expected, got float" errors in karaoke.py

### ISSUE THREAD

**Issue by Romeo1984** [xuancong84/pikaraoke#13]
$ sudo python3 app.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
[2023-04-14 23:34:09] INFO: Fetching available songs in: /usr/lib/pikaraoke/songs/
[2023-04-14 23:34:10] INFO: VLC command base: /usr/bin/cvlc --fullscreen --play-and-exit --extraintf http --http-port 5002 --http-password DtajgJKTRMZoTK0KR8G41VBQ1ezYjZK3 --no-embedded-video --no-keyboard-events --no-mouse-events --video-on-top --volume-save --no-video-title --no-loop --no-repeat --mouse-hide-timeout 0 --intf dummy
Traceback (most recent call last):
  File "app.py", line 967, in <module>
    K = karaoke.Karaoke(args)
  File "/home/pi/pikaraoke/karaoke.py", line 190, in __init__
    self.initialize_screen(not args.windowed)
  File "/home/pi/pikaraoke/karaoke.py", line 300, in initialize_screen
    self.toggle_full_screen(fullscreen)
  File "/home/pi/pikaraoke/karaoke.py", line 314, in toggle_full_screen
    self.render_splash_screen()
  File "/home/pi/pikaraoke/karaoke.py", line 340, in render_splash_screen
    self.logo1 = pygame.transform.scale **(self.logo, (W, H))**
TypeError: integer argument expected, got float

 $ sudo python3 app.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
[2023-04-14 23:40:04] INFO: Fetching available songs in: /usr/lib/pikaraoke/songs/
[2023-04-14 23:40:05] INFO: VLC command base: /usr/bin/cvlc --fullscreen --play-and-exit --extraintf http --http-port 5002 --http-password IT8DRMa8zBDtq8oXGkNicmPpuPAlHPWD --no-embedded-video --no-keyboard-events --no-mouse-events --video-on-top --volume-save --no-video-title --no-loop --no-repeat --mouse-hide-timeout 0 --intf dummy
Traceback (most recent call last):
  File "app.py", line 967, in <module>
    K = karaoke.Karaoke(args)
  File "/home/pi/pikaraoke/karaoke.py", line 190, in __init__
    self.initialize_screen(not args.windowed)
  File "/home/pi/pikaraoke/karaoke.py", line 300, in initialize_screen
    self.toggle_full_screen(fullscreen)
  File "/home/pi/pikaraoke/karaoke.py", line 314, in toggle_full_screen
    self.render_splash_screen()
  File "/home/pi/pikaraoke/karaoke.py", line 348, in render_splash_screen
    self.p_image1 = pygame.transform.scale(self.p_image, **self.normalize((qr_size, qr_size)))**
TypeError: integer argument expected, got float

**Comment by Romeo1984** [comment]
Switched from Python to Miniconda. This is no longer present.
