### ISSUE TITLE
not launching on ubuntu server 20.04

### ISSUE THREAD

**Issue by djlongy** [xuancong84/pikaraoke#5]
I'm trying to get this to run on a ubuntu server x86 machine but it doesn't seem to work.

I've follow the following steps using a fresh install of ubuntu server 20.04
git clone https://github.com/xuancong84/pikaraoke.git
wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh && chmod +x Anaconda3-2021.11-Linux-x86_64.sh
./Anaconda3-2021.11-Linux-x86_64.sh
cd pikaraoke
pip install -r requirements.txt
export PATH=$HOME/anaconda3/bin:$PATH
sudo apt install ffmpeg vlc tmux
PATH=~/anaconda3/bin:$PATH ./run.sh

All the above seems to complete without much issue, except for some errors when trying to download Downloading futures-3.0.0.tar.gz versions.

ERROR: Command errored out with exit status 1:
     command: /home/user/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-woojsbh4/futures_71b7735f1a424192bbcb18dc6fc7a33a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-woojsbh4/futures_71b7735f1a424192bbcb18dc6fc7a33a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wlqy2pzb
         cwd: /tmp/pip-install-woojsbh4/futures_71b7735f1a424192bbcb18dc6fc7a33a/
    Complete output (24 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/home/user/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 32, in <module>
        from setuptools.extern.more_itertools import unique_everseen
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 565, in module_from_spec
      File "/home/user/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py", line 52, in create_module
        return self.load_module(spec.name)
      File "/home/user/anaconda3/lib/python3.9/site-packages/setuptools/extern/__init__.py", line 37, in load_module
        __import__(extant)
      File "/home/user/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py", line 1, in <module>
        from .more import *  # noqa
      File "/home/user/anaconda3/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py", line 5, in <module>
        from concurrent.futures import ThreadPoolExecutor
      File "/tmp/pip-install-woojsbh4/futures_71b7735f1a424192bbcb18dc6fc7a33a/concurrent/futures/__init__.py", line 8, in <module>
        from concurrent.futures._base import (FIRST_COMPLETED,
      File "/tmp/pip-install-woojsbh4/futures_71b7735f1a424192bbcb18dc6fc7a33a/concurrent/futures/_base.py", line 354
        raise type(self._exception), self._exception, self._traceback
                                   ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ea/c9/35287369718fc05059e7a9d0d73c53745fe981010b4185b3858e7d46eff1/futures-3.0.0.tar.gz#sha256=d9cd7bb09aa01f0e4940af64c31fbd7045098b7b4354420d7838ea39e8b86ee3 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
------------------------------

When trying to launch pikaraoke the follow shows
PATH=~/anaconda3/bin:$PATH ./run.sh

  File "/home/user/pikaraoke/karaoke.py", line 200, in __i │ xwininfo: error: unable to open display ":0.0"
nit__                                                     │ None of those TCP/IP swiss army knives installed on this sy
    self.initialize_screen(not window_mode)               │ stem: ncat, socat, tcpserver, socket.
  File "/home/user/pikaraoke/karaoke.py", line 289, in ini│ (base) user@localhost:~/pikaraoke$
tialize_screen                                            │
    pygame.mouse.set_visible(0)                           │
pygame.error: video system not initialized                │
(base) user@localhost:~/pikaraoke$

HDMI is plugged in and I can see the output of the terminal screen.

Does this need to run on ubuntu desktop instead?

**Comment by xuancong84** [comment]
Yes, this needs to be run under a Desktop environment, you can either install the default Ubuntu desktop, or any other desktop environment such as KDE, XFCE, etc.. After that, you must make sure GUI programs such as `xclock` must be able to run successfully. Looking at your error message, I am pretty sure you cannot run `xclock` now.
